-- Run from the repository root: lua tests/smoke.lua
local M = dofile('mod/lua/ge/extensions/avatarSandbox/main.lua')
local player = {x = 0, y = 0, z = 0}
local near = {x = 3, y = 0, z = 0}
local calls = 0
M.onExtensionLoaded()
assert(not M.status().enabled)
assert(not M.setEnabled('yes'))
assert(M.setEnabled(true))
assert(M.registerTarget('cube', 'Test cube', function(id)
  assert(id == 'cube')
  calls = calls + 1
end))
assert(not M.registerTarget('cube', 'Duplicate', function() end))
assert(not M.setTarget('cube', player, near, false))
assert(not M.interact())
assert(not M.setTarget('cube', player, {x = 3.01, y = 0, z = 0}, true))
assert(not M.setTarget('cube', player, {x = 0/0, y = 0, z = 0}, true))
assert(M.setTarget('cube', player, near, true))
assert(M.status().targetLabel == 'Test cube')
assert(M.interact() and calls == 1)
assert(not M.interact())
assert(M.setTarget('cube', player, near, true))
M.onUpdate()
assert(not M.interact())
assert(M.setTarget('cube', player, near, true))
assert(not M.setTarget('missing', player, near, true))
assert(not M.interact())
assert(M.setTarget('cube', player, near, true))
M.unregisterTarget('cube')
assert(not M.interact())
assert(M.registerTarget('broken', 'Broken callback', function() error('test') end))
assert(M.setTarget('broken', player, near, true))
assert(not M.interact())
assert(M.setTarget('broken', player, near, true))
M.setEnabled(false)
assert(not M.interact())
M.onClientEndMission()
assert(M.status().targetCount == 0 and not M.status().enabled)
M.setEnabled(true)
M.registerTarget('cleanup', 'Cleanup', function() end)
M.onExtensionUnloaded()
assert(M.status().targetCount == 0 and not M.status().enabled)
print('Interaction smoke checks passed')
