/* Compile/link instructions are in docs/CROSS_GAME_SUPPORT.md. */
#include "avatar_physics.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>
_Static_assert(sizeof(AvatarProfileV1)==112, "profile ABI layout");
_Static_assert(sizeof(AvatarState)==56 && offsetof(AvatarState,grounded)==48, "state ABI layout");
_Static_assert(sizeof(AvatarCameraPoseV1)==80 && offsetof(AvatarCameraPoseV1,heading)==56, "camera ABI layout");
int main(void) {
    assert(avatar_abi_version() == 1);
    uint64_t avatar = avatar_create(0, 0, 0.7651);
    assert(avatar);
    AvatarTriangle floor = {1, {{-10,-10,0}, {10,-10,0}, {0,10,0}}};
    assert(avatar_set_mesh(avatar, &floor, 1) == 0);
    for (int i = 0; i < 240; ++i) assert(avatar_step(avatar, 1, 0, 0) == 0);
    AvatarState state;
    assert(avatar_get_state(avatar, &state) == 0);
    assert(state.grounded && state.position[0] > 4 && fabs(state.position[2]-0.765) < 0.002);
    assert(avatar_step(avatar, 0, 0, 1) == 0);
    assert(avatar_get_state(avatar, &state) == 0);
    assert(!state.grounded && state.velocity[2] > 15);
    assert(avatar_destroy(avatar) == 0);
    assert(avatar_step(avatar, 0, 0, 0) == -1);
    AvatarProfileV1 profile;
    assert(avatar_default_profile_v1(&profile) == 0);
    profile.walk_speed = 2;
    avatar = avatar_create_with_profile_v1(&profile, 0, 0, 0.7651);
    assert(avatar && avatar_set_mesh(avatar, &floor, 1) == 0);
    for (int i = 0; i < 240; ++i) assert(avatar_step(avatar, 1, 0, 0) == 0);
    assert(avatar_get_state(avatar, &state) == 0);
    assert(state.position[0] > 1.9 && state.position[0] < 2.01);
    assert(avatar_destroy(avatar) == 0);
    profile.radius = -1;
    assert(avatar_create_with_profile_v1(&profile, 0, 0, 1) == 0);
    assert(avatar_create_with_profile_v1(NULL, 0, 0, 1) == 0);
    assert(avatar_default_profile_v1(NULL) == -2);
    avatar = avatar_create(0, 0, 0.7651);
    assert(avatar);
    AvatarTriangle platform = floor;
    platform.id = 2;
    /* Zero displacement establishes grounding on the initial deck. */
    assert(avatar_step_platform_v1(avatar,0,0,0,&platform,1,0,0,0)==0);
    for (int i=0; i<240; ++i) {
        assert(avatar_step_platform_v1(avatar,0,0,0,&platform,1,0.002,0,0.001)==0);
        for (int v=0; v<3; ++v) { platform.vertices[v][0]+=0.002; platform.vertices[v][2]+=0.001; }
    }
    assert(avatar_get_state(avatar,&state)==0);
    assert(state.grounded && fabs(state.position[0]-0.48)<0.001);
    assert(fabs(state.position[2]-1.0051)<0.001);
    AvatarState before = state;
    assert(avatar_step_platform_v1(avatar,0,0,0,NULL,1,0,0,0)==-2);
    assert(avatar_step_platform_v1(avatar,0,0,0,&platform,1,NAN,0,0)==-2);
    assert(avatar_get_state(avatar,&state)==0 && state.position[0]==before.position[0]);
    assert(avatar_set_mesh(avatar,&platform,1)==0);
    assert(avatar_step_platform_v1(avatar,0,0,0,&platform,1,0,0,0)==-2);
    assert(avatar_set_mesh(avatar,NULL,0)==0);
    assert(avatar_step_platform_v1(avatar,0,0,1,&platform,1,0.002,0,0.001)==0);
    assert(avatar_get_state(avatar,&state)==0 && !state.grounded);
    assert(state.velocity[0]>0.4 && state.velocity[2]>15.8);
    assert(avatar_destroy(avatar)==0);
    assert(avatar_step_platform_v1(avatar,0,0,0,NULL,0,0,0,0)==-1);
    avatar = avatar_create(0,0,1);
    double focus[3]={0,0,1}, eye[3]={0,0,1.4};
    AvatarCameraPoseV1 camera;
    assert(avatar_camera_pose_v1(avatar,focus,eye,-1,&camera)==-2);
    assert(avatar_camera_active_v1(avatar,1)==0);
    assert(avatar_camera_zoom_v1(avatar,-6)==0);
    assert(avatar_camera_pose_v1(avatar,focus,eye,-1,&camera)==0);
    assert(camera.first_person==1 && camera.position[2]==1.4);
    assert(avatar_camera_zoom_v1(avatar,8)==0);
    assert(avatar_camera_pose_v1(avatar,focus,eye,0.5,&camera)==0);
    assert(camera.first_person==0 && fabs(camera.actual_distance-1.9)<1e-10);
    assert(avatar_camera_look_v1(avatar,NAN,0)==-2);
    assert(avatar_destroy(avatar)==0);
    /* Additive calibration APIs; frozen structs and legacy camera still work. */
    assert(avatar_studio_r6_profile_v1(&profile)==0);
    assert(avatar_studio_r6_profile_v1(NULL)==-2);
    assert(profile.ground_acceleration>220 && profile.air_acceleration>42);
    avatar=avatar_create_with_profile_v1(&profile,0,0,profile.height/2+0.0001);
    assert(avatar && avatar_set_mesh(avatar,&floor,1)==0);
    assert(avatar_motor_response_v1(avatar,150)==0);
    assert(avatar_motor_response_v1(avatar,NAN)==-2);
    assert(avatar_motor_response_v1(avatar,241)==-2);
    for (int i=0;i<240;++i) assert(avatar_step(avatar,0.5,0,0)==0);
    assert(avatar_get_state(avatar,&state)==0 && fabs(state.velocity[0]-2.4)<1e-8);
    assert(avatar_motor_caps_v1(avatar,0,0)==0);
    assert(avatar_motor_caps_v1(avatar,-1,43)==-2);
    assert(avatar_step(avatar,-1,0,0)==0);
    assert(avatar_get_state(avatar,&state)==0 && fabs(state.velocity[0]-2.4)<1e-8);
    assert(avatar_camera_classic_v1(avatar,0.3)==0);
    assert(avatar_camera_active_v1(avatar,1)==0);
    assert(avatar_camera_distance_v1(avatar,0.297)==0);
    assert(avatar_camera_advance_v1(avatar,1,-1)==0);
    assert(avatar_camera_pose_v1(avatar,focus,eye,-1,&camera)==0);
    assert(camera.first_person && fabs(camera.actual_distance-0.15)<1e-8);
    assert(avatar_camera_zoom_v1(avatar,1)==0);
    assert(avatar_camera_advance_v1(avatar,1,-1)==0);
    assert(avatar_camera_pose_v1(avatar,focus,eye,-1,&camera)==0);
    assert(!camera.first_person && fabs(camera.requested_distance-0.525)<1e-8);
    assert(avatar_camera_advance_v1(avatar,0.1,0.1)==0);
    assert(avatar_camera_pose_v1(avatar,focus,eye,-1,&camera)==0 && camera.actual_distance<=0.1);
    assert(avatar_destroy(avatar)==0);
    avatar=avatar_create(0,0,1);
    AvatarBoundsV1 player={{20,20,20},{21,21,21}}, bounds;
    double centre[3]={0.5,0.5,0.5}, offset[3]={2,0,0};
    uint64_t part=0;
    assert(avatar_building_edit_v1(avatar,0,0,centre,&player,NULL,0,&part)==-2);
    assert(avatar_building_enabled_v1(avatar,1)==0);
    assert(avatar_building_preview_v1(avatar,centre,&player,NULL,0,&bounds)==0 && bounds.min[0]==0);
    assert(avatar_building_get_v1(avatar,1,&bounds)==-2);
    assert(avatar_building_edit_v1(avatar,0,0,centre,&player,NULL,0,&part)==0);
    assert(avatar_building_edit_v1(avatar,1,part,offset,&player,NULL,0,&part)==0);
    assert(avatar_building_get_v1(avatar,part,&bounds)==0 && bounds.min[0]==2);
    assert(avatar_building_clear_v1(avatar)==0);
    assert(avatar_building_get_v1(avatar,part,&bounds)==-2);
    assert(avatar_destroy(avatar)==0);
    avatar=avatar_create(0,0,1);
    AvatarInputV1 inputs[16]; AvatarDriverStatusV1 driver_status; uint32_t count=99;
    assert(avatar_driver_control_v1(avatar,0,1)==0);
    assert(avatar_driver_control_v1(avatar,3,1)==0);
    assert(avatar_driver_batch_v1(avatar,1.0/60.0,inputs,&count,&driver_status)==0 && count==4);
    assert(fabs(hypot(inputs[0].movement[0],inputs[0].movement[1])-1)<1e-10);
    count=99;
    assert(avatar_driver_batch_v1(avatar,NAN,inputs,&count,&driver_status)==-2 && count==99);
    assert(avatar_driver_batch_v1(avatar,0,inputs,&count,&driver_status)==0 && count==0);
    assert(avatar_driver_batch_v1(avatar,1,inputs,&count,&driver_status)==0 && count==16);
    assert(driver_status.dropped_seconds>0.9 && inputs[0].movement[0]==0);
    assert(avatar_driver_control_v1(avatar,5,1)==-2);
    assert(avatar_driver_reset_v1(avatar)==0);
    assert(avatar_destroy(avatar)==0);
    assert(avatar_driver_heading_v1(avatar,0)==-1);
    AvatarPoseV1 identity={{0,0,0},{0,0,0,1}}, pose;
    assert(avatar_pose_blend_v1(&identity,&identity,0.5,&pose)==0 && pose.rotation[3]==1);
    assert(avatar_pose_blend_v1(&identity,&identity,NAN,&pose)==-2);
    assert(avatar_pose_retarget_v1(&identity,&identity,&identity,&identity,&pose)==0);
    avatar=avatar_create(0,0,1);
    AvatarGearCommandV1 command; double origin[3]={0,0,1}, direction[3]={0,1,0};
    assert(avatar_gear_equip_v1(avatar,7)==-2);
    assert(avatar_gear_equip_v1(avatar,2)==0);
    assert(avatar_gear_activate_v1(avatar,origin,direction,0,0,&command)==0);
    assert(command.effect==1 && command.flags==7 && command.speed==18);
    assert(avatar_gear_activate_v1(avatar,origin,direction,0,0,&command)==-2);
    assert(avatar_gear_advance_v1(avatar,7)==0);
    assert(avatar_gear_activate_v1(avatar,origin,direction,0,0,&command)==0);
    assert(avatar_gear_reset_v1(avatar)==0);
    assert(avatar_gear_building_enabled_v1(avatar,1)==0);
    assert(avatar_gear_equip_v1(avatar,7)==0);
    assert(avatar_gear_activate_v1(avatar,origin,direction,2,42,&command)==0 && command.block_id==42);
    assert(avatar_destroy(avatar)==0);
    avatar=avatar_create(0,0,1);
    AvatarKeyV1 keys[2]={{0,{{0,0,0},{0,0,0,1}},0},{1,{{2,0,0},{0,0,1,0}},0}};
    assert(avatar_track_upload_v1(avatar,10,keys,2)==0);
    assert(avatar_track_sample_v1(avatar,10,0.5,0,&pose)==0 && pose.translation[0]==1);
    keys[1].time=0;
    assert(avatar_track_upload_v1(avatar,10,keys,2)==-2);
    assert(avatar_track_sample_v1(avatar,10,0.5,0,&pose)==0 && pose.translation[0]==1);
    AvatarMotionV1 motion={1,1,0,0,4.8};AvatarSelectionV1 selection;
    assert(avatar_animation_update_v1(avatar,0.01,&motion,&selection)==0 && selection.clip==1 && selection.changed==1);
    motion.active=0;
    assert(avatar_animation_update_v1(avatar,0.01,&motion,&selection)==0 && selection.active==0);
    assert(avatar_animation_reset_v1(avatar)==0);
    assert(avatar_track_sample_v1(avatar,10,0,0,&pose)==-2);
    AvatarIdV1 hash={{0}},requested,resolved;memset(hash.bytes,'a',64);
    assert(avatar_catalogue_configure_v1(avatar,&hash,1,NULL,0)==0);
    assert(avatar_catalogue_change_v1(avatar,0,12,NULL)==0);
    assert(avatar_catalogue_change_v1(avatar,1,12,&hash)==0);
    AvatarAssignmentV1 assignments[256];uint64_t revision;
    assert(avatar_catalogue_snapshot_v1(avatar,assignments,&count,&revision)==0 && count==1);
    assert(avatar_catalogue_apply_v1(avatar,1,revision,assignments,count)==0);
    assert(avatar_catalogue_get_v1(avatar,12,&requested,&resolved)==0);
    assert(memcmp(requested.bytes,hash.bytes,65)==0 && strcmp((char*)resolved.bytes,"noob")==0);
    assert(avatar_catalogue_apply_v1(avatar,1,revision,assignments,count)==-2);
    assignments[1]=assignments[0];
    assert(avatar_catalogue_apply_v1(avatar,1,revision+1,assignments,2)==-2);
    assert(avatar_catalogue_client_reset_v1(avatar)==0);
    assert(avatar_catalogue_apply_v1(avatar,1,0,NULL,0)==0);
    assert(avatar_catalogue_get_v1(avatar,12,&requested,&resolved)==-2);
    hash.bytes[64]='b';
    assert(avatar_catalogue_configure_v1(avatar,&hash,1,NULL,0)==-2);
    assert(avatar_catalogue_change_v1(avatar,2,12,NULL)==0);
    assert(avatar_destroy(avatar)==0);
    puts("C host: profiles, platform carry/jump, validation and lifecycle passed");
    return 0;
}
